import { FamilyMember, RecordType, User } from './types';

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Azizbek Rahimov',
  avatarUrl: 'https://picsum.photos/id/64/200/200',
  familyMembers: [
    {
      id: 'm1',
      name: 'Azizbek',
      relation: 'O\'zi',
      age: 32,
      bloodType: 'A+',
      avatarUrl: 'https://picsum.photos/id/64/200/200',
      healthOverview: 'Oxirgi hafta yurak urishi barqaror. G‘ayrioddiy o‘zgarishlar aniqlanmadi.',
      stats: { 
        heartRate: 72, 
        weight: 78, 
        height: 180,
        lastUpdated: 'Bugun, 08:30',
        heartRateInsight: 'Bu yosh uchun yurak urishi normal oraliqda.',
        growthInsight: 'O‘lchovlar barqaror saqlanmoqda.' 
      },
      reminders: [
        {
          id: 'rem1',
          title: 'Amoksitsillin ichish',
          subtitle: '500mg, ovqatdan keyin',
          date: 'Bugun 14:00',
          type: 'medication',
          urgent: true,
        },
        {
          id: 'rem2',
          title: 'Qon tahlili topshirish',
          subtitle: 'Xolesterin tekshiruvi',
          date: 'Ertaga 09:00',
          type: 'analysis',
          urgent: false,
        }
      ],
      records: [
        {
          id: 'r1',
          type: RecordType.CHECKUP,
          title: 'Yillik Kardiologiya Tekshiruvi',
          date: '2024-05-12',
          doctor: 'Dr. Karimov',
          summary: 'Qon bosimi biroz yuqori. Tuz iste\'molini kamaytirish tavsiya etildi.',
          relevance: 'Yurak-qon tomir salomatligini nazorat qilish uchun muhim.',
          source: 'Manba: Shifokor qaydi',
          createdAt: '12 May, 14:20',
          riskLevel: 'Low',
        },
        {
          id: 'r2',
          type: RecordType.LAB_RESULT,
          title: 'Umumiy Qon Tahlili',
          date: '2024-05-10',
          summary: 'Gemoglobin darajasi normal. Xolesterin me\'yorida.',
          relevance: 'Umumiy salomatlik ko\'rsatkichlarini baholash.',
          source: 'Manba: Laboratoriya integratsiyasi',
          createdAt: '10 May, 09:15',
          riskLevel: 'Low',
        },
        {
          id: 'r4',
          type: RecordType.PRESCRIPTION,
          title: 'Antibiotik kursi',
          date: '2023-12-15',
          doctor: 'Dr. Smith',
          summary: 'O\'tkir bronxit uchun yozilgan.',
          relevance: 'Infeksiyani davolash uchun zarur.',
          source: 'Manba: Retsept skaneri',
          createdAt: '15 Dec 2023',
          riskLevel: 'Medium',
        },
        {
          id: 'r5',
          type: RecordType.VACCINATION,
          title: 'Gepatit B vaksinasi',
          date: '2023-06-20',
          summary: 'Rejali buster dozasi muvaffaqiyatli qilindi.',
          relevance: 'Virusli gepatitdan himoya qiladi.',
          source: 'Manba: Emlash kartasi',
          createdAt: '20 Jun 2023',
          riskLevel: 'Low',
        },
        {
          id: 'r6',
          type: RecordType.CHECKUP,
          title: 'Terapevt ko\'rigi',
          date: '2022-11-05',
          doctor: 'Dr. Karimov',
          summary: 'Doimiy bosh og\'rig\'i shikoyati. MRI tavsiya qilindi.',
          relevance: 'Surunkali og\'riq sababini aniqlash.',
          source: 'Manba: Ambulator karta',
          createdAt: '05 Nov 2022',
          riskLevel: 'Medium',
        }
      ],
    },
    {
      id: 'm2',
      name: 'Malika',
      relation: 'Turmush o\'rtog\'i',
      age: 29,
      bloodType: 'O+',
      avatarUrl: 'https://picsum.photos/id/65/200/200',
      healthOverview: 'Umumiy holat a\'lo.',
      stats: { 
        heartRate: 75, 
        weight: 60, 
        height: 165,
        lastUpdated: '3 kun oldin',
        heartRateInsight: 'Normal holat.',
        growthInsight: 'Barqaror.'
      },
      reminders: [],
      records: [],
    },
    {
      id: 'm3',
      name: 'Amir',
      relation: 'O\'g\'li',
      age: 5,
      bloodType: 'A+',
      avatarUrl: 'https://picsum.photos/id/342/200/200',
      healthOverview: 'So‘nggi 6 oyda nafas yo‘llari bilan bog‘liq shikoyatlar takrorlangan.',
      stats: { 
        heartRate: 90, 
        weight: 22, 
        height: 110,
        lastUpdated: 'Kecha, 18:00',
        heartRateInsight: 'Bolalar uchun normal ko\'rsatkich.',
        growthInsight: 'O‘sish ma’lumotlari saqlandi. Vaqt o‘tishi bilan solishtirish mumkin.'
      },
      reminders: [
         {
          id: 'rem3',
          title: 'Polio Emlash',
          subtitle: 'Milliy emlash kunlari',
          date: 'Kelasi hafta',
          type: 'vaccination',
          urgent: false,
        }
      ],
      records: [
        {
          id: 'r3',
          type: RecordType.VACCINATION,
          title: 'Grippga qarshi vaksina',
          date: '2023-11-20',
          doctor: 'Dr. Aliyeva',
          summary: 'Mavsumiy grippga qarshi emlash qayd etildi. Nojo‘ya ta’sirlar kuzatilmadi. Qisqa muddatli xavf past.',
          relevance: 'Immunitet holatini kuzatishga yordam beradi.',
          source: 'Manba: Emlash daftarchasi',
          createdAt: '20 Nov 2023',
          riskLevel: 'Low',
        },
        {
            id: 'r7',
            type: RecordType.CHECKUP,
            title: 'O\'sish nazorati',
            date: '2023-05-15',
            doctor: 'Dr. Aliyeva',
            summary: 'Bo\'y va vazn ko\'rsatkichlari a\'lo. Sog\'lom o\'sish.',
            relevance: 'Jismoniy rivojlanishni monitoring qilish.',
            source: 'Manba: Tibbiy ko\'rik',
            createdAt: '15 May 2023',
            riskLevel: 'Low',
        }
      ],
    },
  ],
};